# Generated by Django 4.0.5 on 2022-06-29 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WatchMate', '0003_rename_storyline_streamplateform_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='WatchMate.streamplateform'),
            preserve_default=False,
        ),
    ]
