# Generated by Django 4.0.6 on 2022-07-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchMate', '0006_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
